mode = "local"
project = ""
shell = ""

[dirs]
project = []
python = "isolated"
data = "/home/eric/.local/share/hatch"
cache = "/home/eric/.cache/hatch"

[dirs.env]

[projects]

[publish.index]
repo = "main"

[template]
name = "Eric T. Johnson"
#email = "yut23@gvljohnsons.com"

[template.licenses]
headers = true
default = [
    "BSD-3-Clause",
]

[template.plugins.default]
tests = true
ci = true
src-layout = true

[terminal.styles]
info = "bold"
success = "bold cyan"
error = "bold red"
warning = "bold yellow"
waiting = "bold magenta"
debug = "bold"
spinner = "simpleDotsScrolling"
